import NavBar from "@/components/NavBar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default:'Learning Next Js', // a fallback for any child route that doesn't have the title
    template:'%s | Learning Next Js', // to add prefix or suffix to the title of child route
    absolute:'', // To allow the child route to break from the template pattern set by parent segment
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <NavBar/>

        {children}
        <footer className="bg-blue-500 p-2">
          <p>© 2025 Learning Next Js</p>
        </footer>
      </body>
    </html>
  );
}
